server:
  port: 8081
spring:
  application:
    name: msvc-teacher
  datasource:
    url: jdbc:postgresql://localhost:5432/teacherdb
    username: postgres
    password: 7530
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
